spring.application.name=api-gateway
server.port=8080

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=http://eureka-server.railway.internal:8761/eureka

# Machine Service
spring.cloud.gateway.server.webmvc.routes[0].id=machine-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MACHINE-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/machines/**

# Production Service
spring.cloud.gateway.server.webmvc.routes[1].id=production-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PRODUCTION-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/production/**

# Quality Service - USE SAME FORMAT!
spring.cloud.gateway.server.webmvc.routes[2].id=quality-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://QUALITY-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/quality/**