# Service Configuration
spring.application.name=quality-service
server.port=${PORT:8084}

# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/quality_db
#spring.datasource.username=postgres
#spring.datasource.password=Bharath

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://quality-db:5432/quality_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Configuration
eureka.client.service-url.defaultZone=https://eureka-serverr.up.railway.app/eureka
eureka.instance.hostname=${RAILWAY_PRIVATE_DOMAIN:quality-service}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=${PORT:8084}
eureka.instance.instance-id=${spring.application.name}:${random.value}


# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info
